### ISSUE TITLE
inStrain compare: AssertionError: No scaffolds are shared amoung the IS

### ISSUE THREAD

**Issue by celine77** [MrOlm/inStrain#119] opened 2022-10-09 14:41 UTC
Dear Matt,

Thanks for developing such a good tool. I have three questions that I would like to enquire:

1. For Tutorial 3) Merging custom genomes with an existing genome database. If i would like to GTDBtk as a reference is the steps similar as [UHGG]? 

2. When I use inStrain compare, I got follow error: 

    9110 of 9110 scaffolds are in at least 2 samples
    0 of these scaffolds are in the provided list of 11938
    Traceback (most recent call last):
      File "/home/user/miniconda3/bin/inStrain", line 31, in <module>
        inStrain.controller.Controller().main(args)
      File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/controller.py", line 44, in main
        self.compare_operation(args)
      File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/controller.py", line 70, in compare_operation
        inStrain.readComparer.main(args)
      File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/readComparer.py", line 38, in main
        RCprof, names, Sprofiles, scaffolds_to_compare, outbase, s2l = parse_validate(args)
      File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/readComparer.py", line 306, in parse_validate
        assert len(scaffolds_to_compare) > 0, "No scaffolds are shared amoung the IS"
    AssertionError: No scaffolds are shared amoung the IS

For this error, first, i use two samples from two different people. And then I am curious is that just caused by they didn't share any scaffolds? And then when I use two samples from the same person, the error is still. 

Therefore, I wonder, is that because "0 of these scaffolds are in the provided list of 11938"? If this is the case, what should I do to deal with the STB file? is there any suggestion about the binning result name for stb file preparation? 

3. By the way, there is another potential reason, when i run inStrain profile, 

    Scaffold to bin was made using .stb file
    Could not load .fasta file allGenomes_v1.fa; will not GC correct iRep

Is that because the "combining all of the genomes that you’d like to map into a single .fasta file." or the stb file  is not prepare well?

Looking forward to your kind reply. Thanks.

Celine

**Comment by MrOlm** [comment] 2022-10-10 23:33
Hi Celine,

1) I have never actually this with GTDB, but yes the steps should be the same as with UHGG

2,3) Yes, these errors are almost definitely because inStrain is not able to properly read your .stb or .fasta files. Could you send a brief snippit of what your .fasta file headers and .stb file look like?

-Matt

**Comment by celine77** [comment] 2022-10-11 01:55
Dear Matt,

Thanks for your reply. 

The headers of .stb file is as below:
    k77_65100	ag1.megahit.metabat2.bin.1.fa
    k77_455506	ag1.megahit.metabat2.bin.1.fa
    k77_309	ag1.megahit.metabat2.bin.1.fa
    k77_195546	ag1.megahit.metabat2.bin.1.fa
    k77_325817	ag1.megahit.metabat2.bin.1.fa
    k77_196363	ag1.megahit.metabat2.bin.1.fa

The headers of .fa file is as below:
     >k77_65100
    CAGGGAAATATCTTTGCCTTTTATTTCGGATAAAACAGTGGCAGGAAGTACCTTGGCACC
    ATTCAGGGTAATGGAAACGGTATCTTTTTCTTTGGAAGCCCTGATCAGATCATTGACAGC

These two files are created from binning genomes with the below code:

    cat /home/results/09.dereplicate/genomes/hmq.bins.drep.out/dereplicated_genomes/*.fa > allGenomes_v1.fa

    #### Create a scaffold-to-bin file from the genome set.
    cd /home/results/09.dereplicate/genomes/hmq.bins.drep.out/dereplicated_genomes
    parse_stb.py --reverse -f ./* -o representitve_genomes.stb
    
    #### bowtie2
    mkdir bt2
    module load bowtie2-2.4.2
    bowtie2-build ./allGenomes_v1.fa bt2/allGenomes_v1.fa

Any suggestion will be much appreciated! Thanks.

Best,
Celine

**Comment by MrOlm** [comment] 2022-10-11 01:58
Interesting... would you mind sending me `allGenomes_v1.fa`? My email is mattolm@gmail.com . I wonder if there is a problem in the file somewhere that's causing the bug `could not load .fasta file`

**Comment by celine77** [comment] 2022-10-11 04:07
Dear Matt,

Thanks for your reply. Have sent it to your email.  
Looking forward to your kind reply. Thanks.

Celine

**Comment by MrOlm** [comment] 2022-10-11 17:23
Hi @celine77 - 

I see now that the problem is that some scaffolds have the same names (for example, `k77_91838` appears twice). This is almost certainly causing these problems.

I will work on a more permanent solution to fix this, but in the meantime I can suggest a hack to fix it. Before concatenating genomes, you can rename all scaffolds to include the name of the scaffold in the genome name using a command like the following:

```
for f in $(ls *); do cat $f | sed  "s|>|>$f\_|g" > renamed_bins/$f; done
```

You can then concatenate the files in the `renamed_bins` folder and generate a new `.stb` file from the genomes in that folder as well.

Let me know if you have any questions

-MO

**Comment by celine77** [comment] 2022-10-13 01:46
Dear Matt,

Thanks for your kind solution. 

I have tried your suggested method and it really didn't have this error "Could not load .fasta file allGenomes_v1.fa; will not GC correct iRep" in profile step anymore.

But when I finish the profile and do instrain comparison. The error are still here:

      7271 of 11226 scaffolds are in at least 2 samples
      0 of these scaffolds are in the provided list of 12022
      Traceback (most recent call last):
        File "/home/user/miniconda3/bin/inStrain", line 31, in <module>
          inStrain.controller.Controller().main(args)
        File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/controller.py", line 44, in main
          self.compare_operation(args)
        File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/controller.py", line 70, in compare_operation
          inStrain.readComparer.main(args)
        File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/readComparer.py", line 38, in main
          RCprof, names, Sprofiles, scaffolds_to_compare, outbase, s2l = parse_validate(args)
        File "/home/user/miniconda3/lib/python3.9/site-packages/inStrain/readComparer.py", line 306, in parse_validate
          assert len(scaffolds_to_compare) > 0, "No scaffolds are shared amoung the IS"
      AssertionError: No scaffolds are shared amoung the IS

Is it possible that there two samples really didn't share the same strain? but seems that if I use the IS. file of the same sample, the error is still there.
Or would you suggest that I share the log file of both profile and compare them with you?

Looking forward to your kind reply. Many thanks.

Best,
Celine

**Comment by MrOlm** [comment] 2022-10-13 01:49
Hi Celine,

Are you sure you're using the .stb file created from the renamed_bins? If you used the original .stb file that would explain this error.

Best,
Matt

**Comment by celine77** [comment] 2022-10-13 02:07
Dear Matt,

Thanks for your kind confirmation. Yeah. I used the renamed one.

The header of stb. is as below,

      ag1.megahit.metabat2.bin.1.fa_k77_65100	ag1.megahit.metabat2.bin.1.fa
      ag1.megahit.metabat2.bin.1.fa_k77_455506	ag1.megahit.metabat2.bin.1.fa
      ag1.megahit.metabat2.bin.1.fa_k77_309	ag1.megahit.metabat2.bin.1.fa
      ag1.megahit.metabat2.bin.1.fa_k77_195546	ag1.megahit.metabat2.bin.1.fa

I am installing the public dataset and will try to use it as reference genomes first to see what will happen.

Best,
Celine

**Comment by MrOlm** [comment] 2022-10-13 17:04
Hi Celine,

Interesting. Could you send me the files `raw_data/scaffold2length.json` in the two new inStrain profile runs, as well as the new .stb file? That will help me ID what the problem is.

-MO

**Comment by celine77** [comment] 2022-10-19 03:57
Dear Matt,

I am happy to tell you it seems the strain compare works, finally!!! 

As I mentioned at the first beginning, the main error is :
      9110 of 9110 scaffolds are in at least 2 samples
      0 of these scaffolds are in the provided list of 11938

I previously created the stb. file using [parse_stb.py script] and generally it creates two columns.
After I delete the second column of the stb file. I know it's weird but it works!!! 
If you have any idea about why it works after that, pls share your idea~ 

Really thanks for your time for helping check the files several times vai email and debug the “rename” issue, which is really essential!

Best,
Celine

**Comment by MrOlm** [comment] 2022-10-20 02:58
OK this is super helpful information, and I'm sorry I haven't responded to your most recent email (very busy past few days). Just a couple of clarification questions-

1) The log that you sent previously says "1874 of 2776 scaffolds are in at least 2 samples
0 of these scaffolds are in the provided list of 15569", but above you wrote "9110 of 9110 scaffolds are in at least 2 samples
0 of these scaffolds are in the provided list of 11938"

Just want to confirm- when you deleted the second column, it was for the run with 2776 or 9110 scaffolds?

2) Could you send me the modified (working) .stb file, as well as the log.log file from the (working) instrain compare command?

As you suspect, without that second column we won't be able to get the "genomeWide_compare.tsv"  file, but with the info I asked for here I should be able to fix this bug for good.

Thanks,
Matt

**Comment by MrOlm** [comment] 2022-10-20 03:04
Hi Celine,

Apologies!! Looking into this more, I do think this issue is due to running an old version of inStrain!

Update to v1.6.3, either with conda or pip, and I really think this issue will be fixed!

Sorry I didn't realize this sooner,
Matt

**Comment by celine77** [comment] 2022-10-21 07:38
Dear Matt,

Really thanks for your reply and indicating the way out. 

I updated to 1.6.3 version and the stb. file read is no longer a problem for compare step! I will try both two steps and hope everything will be fine!

Thanks again for your time and dedicated efforts!!!

Best,
Celine

I

**Closed** 2022-11-02 00:37 UTC
