### ISSUE TITLE
KeyError running profile function?

### ISSUE THREAD

**Issue by rebeccasophiasalcedo** [MrOlm/inStrain#53] opened 2021-03-23 06:52 UTC
Hi there!

I've been trying to run a simple profile and keep getting a key error after it finishes profiling the genes. I've run instrain successfully in the past with no problem, so I'm not sure what went wrong/if I did anything wrong. I followed the documentation to generate all my input files/install instrain originally.

This is the command I used: inStrain profile SRR706782395+_mapped_to_GBSF.sort.bam GBSF.AOA2.fasta -g GBSF_prodigal_orfs.fna -o GBSF_SRR7067823_instrain

Here's a picture of the error output:
<img width="1257" alt="Screen Shot 2021-03-22 at 11 36 29 PM" src="https://user-images.githubusercontent.com/78378647/112104537-8fc76080-8b68-11eb-86c4-b12649d4d190.png">

Any help would be much appreciated!

-Rebecca

**Comment by MrOlm** [comment] 2021-03-23 15:55
Hi Rebecca,

Sorry this bug is happening and thanks for reaching out, A couple of things. 1) Can you list the files that ended up in the `raw_data` folder after the program crashed? 2) Can you let me know which version of inStrain you're running? (if you run `inStrain -h` it'll show the version near the top of the help. 

Depending on what files you have in your `raw_data` folder, I may ask for you to send me the log file and/or some `raw_data` files so that I can troubleshoot this issue.

Thanks,
Matt

**Comment by rebeccasophiasalcedo** [comment] 2021-03-23 16:42
Thank you for the quick reply!

Here's my raw_data directory contents:

(base) Joses-MBP:raw_data rsalcedo$ ls
Rdic.json				genes_table.csv.gz
_README.txt				mapping_info.csv.gz
attributes.tsv				raw_linkage_table.csv.gz
clonT.hd5				raw_snp_table.csv.gz
clonTR.hd5				scaffold2length.json
covT.hd5				scaffold_2_mm_2_read_2_snvs.pickle
cumulative_scaffold_table.csv.gz	scaffold_list.txt
cumulative_snv_table.csv.gz

and I am running ...::: inStrain v1.5.2 :::...

Best,
Rebecca

**Comment by MrOlm** [comment] 2021-03-23 16:52
OK- thanks for this. I'm 99% sure that the problem is that no genes were found in this sample (no genes have any coverage) which is leading to this crash. I'll push an update as soon as possible to fix this edgecase and post here when the update is ready for download.

Best,
Matt

**Comment by rebeccasophiasalcedo** [comment] 2021-03-23 16:55
Thank you so much! 

-Rebecca

**Comment by MrOlm** [comment] 2021-03-26 22:26
Fixed in version 1.5.3

**Closed by MrOlm** 2021-03-26 22:26 UTC
