### ISSUE TITLE
inStrain compare KeyError: 'covT'

### ISSUE THREAD

**Issue by marina-vn** [MrOlm/inStrain#151] opened 2023-05-22 13:51 UTC
Hi!

I'm struggling with the first step of inStrain compare (v 1.7.1), any idea about how to solve this error?

***************************************************
    ..:: inStrain compare Step 1. Load data ::..

Loading Profiles into RAM:   8%|██████████████▍                                                                                                                                                              | 1/12 [00:00<00:00, 121.90it/s]
Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'covT'

***************************************************

Thanks,

Marina

**Comment by MrOlm** [comment] 2023-05-22 16:36
Hi Marina,

In your inStrain profile folder there should be a folder called `raw_data`, and within that folder there should be a file called `covT`. Is it there? If it's not, could it have been left behind when you copied the folder from one location to another?

Best,
Matt

**Comment by marina-vn** [comment] 2023-05-23 07:26
Hi Matt,

Yes, I have the covT.hd5 files for each profile

**Comment by marina-vn** [comment] 2023-05-24 14:03
Of course,

command:

inStrain compare -i TS_abr.fa.bam_inStrain_profile TS_ago.fa.bam_inStrain_profile TS_dic.fa.bam_inStrain_profile TS_ene.fa.bam_inStrain_profile TS_feb.fa.bam_inStrain_profile TS_jul.fa.bam_inStrain_profile TS_junioCNAG_cat.fa.bam_inStrain_profile TS_mar.fa.bam_inStrain_profile TS_may.fa.bam_inStrain_profile TS_nov.fa.bam_inStrain_profile TS_oct_cat.fa.bam_inStrain_profile TS_sept_cat.fa.bam_inStrain_profile

the complete error message:

***************************************************
    ..:: inStrain compare Step 1. Load data ::..
***************************************************

Loading Profiles into RAM:   8%|█████▎                                                         | 1/12 [00:00<00:00, 87.86it/s]
Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'covT'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/metapop/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/controller.py", line 57, in main
    self.compare_operation(args)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/controller.py", line 89, in compare_operation
    inStrain.compare_controller.CompareController(args).main()
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/compare_controller.py", line 55, in main
    self.create_scaffoldcomparison_objects()
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/compare_controller.py", line 184, in create_scaffoldcomparison_objects
    input2scaffolds=i2s)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/compare_controller.py", line 614, in make_scaffoldcomparison_objects
    scaffolds = list(ISP._get_covt_keys())
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 640, in _get_covt_keys
    filename = self.get_location('raw_data') + '/' + os.path.basename(Adb.loc['covT', 'value'])
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'covT'


I'm also attaching the complete log file: 
[log.log](https://github.com/MrOlm/inStrain/files/11555379/log.log)

**Comment by MrOlm** [comment] 2023-05-24 17:42
OK thank you. This is a weird error. In the "raw_data" folder of `TS_abr.fa.bam_inStrain_profile` there should be a file called `Attributes.tsv` (or something like that). Would you mind pasting the contents of that file here? If that file is not there, could you please list all the files in the `TS_abr.fa.bam_inStrain_profile` raw_data folder?

Also I fixed a bug with a related error in a very recent version of inStrain, and upgrading to that version might help with this issue? v1.7.5

-Matt

**Comment by marina-vn** [comment] 2023-05-25 07:22
Here is the Attributes.tsv file (I renamed it to txt because the tsv format is not supported in GitHub) [[attributes.txt](https://github.com/MrOlm/inStrain/files/11562073/attributes.txt)] and, just in case, the other files in the "raw data" folder are:

>attributes.tsv
>bin2length.json
>clonT.hd5
>clonTR.hd5
>covT.hd5
>cumulative_scaffold_table.csv.gz
>cumulative_snv_table.csv.gz
>genome_level_info.csv.gz
>list_raw_data
>mapping_info.csv.gz
>raw_linkage_table.csv.gz
>raw_snp_table.csv.gz
>Rdic.json
>_README.txt
>scaffold2bin.json
>scaffold2length.json
>scaffold_2_mm_2_read_2_snvs.pickle
>scaffold_list.txt

I'm also updating the version to run it again

**Comment by MrOlm** [comment] 2023-05-25 20:17
OK that's just too weird, because the program is failing to find `covT` in `Attributes.tsv`, but I can see from your upload that it's clearly there. This is not a problem I've ever encountered before.

Looking at the log, though, it seems like the program is actually crashing on `TS_ago.fa.bam_inStrain_profile`. Can you confirm there is a line starting with `covT` in the `attributes.tsv` file of that folder?

If there is, the only way I can reasonably troubleshoot this is if it have the files, unfortunately. I think the easiest way to do this would be to 1) try it with just 2 inStrain profile objects (`TS_abr.fa.bam_inStrain_profile` and `TS_ago.fa.bam_inStrain_profile`, for example), and confirm it still crashes, and then 2) compress and send me those folders (either here or via email) so I can see where the problem is.

Sorry you're having this problem,
Matt

**Comment by marina-vn** [comment] 2023-05-31 10:26
Hi Matt,

I have checked the bam files and performed again the profiles, making sure that the CovT file was present in all of them and then ran again the "compare", but I'm getting a new error message:


***************************************************
    ..:: inStrain compare Step 1. Load data ::..
***************************************************

Loading Profiles into RAM: 100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 24.15it/s]
1 of 1 scaffolds are in at least 2 samples
***************************************************
..:: inStrain compare Step 2. Run comparisons ::..
***************************************************

Running group 1 of 1
Comparing scaffolds: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.05s/it]
***************************************************
..:: inStrain compare Step 3. Auxiliary processing ::..
***************************************************

Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cryptic'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/metapop/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/controller.py", line 57, in main
    self.compare_operation(args)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/controller.py", line 89, in compare_operation
    inStrain.compare_controller.CompareController(args).main()
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/compare_controller.py", line 73, in main
    self.run_auxillary_processing()
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/compare_controller.py", line 297, in run_auxillary_processing
    PM = inStrain.polymorpher.PoolController(self.SC_objects, self.name2bam)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/inStrain/polymorpher.py", line 65, in __init__
    db = db[db['cryptic'] == False]
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/emm4/anaconda3/envs/metapop/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'cryptic'



I'm attaching the log in case it helps
[log.log](https://github.com/MrOlm/inStrain/files/11611822/log.log)



If I do the same but without adding the "bams", the program finishes succesful

I really appreciate your help with this

**Comment by MrOlm** [comment] 2023-05-31 19:30
Ahhh I believe this is an error that I fixed in a recent inStrain update. Please update inStrain to the latest version- I think that will fix it. `pip install inStrain --upgrade`

Best,
Matt

**Comment by marina-vn** [comment] 2023-06-06 10:21
Hi Matt,

I have updated the program and make sure that every profile had generated the covT file and it works 

One last question, I'm working with files that contain pair reads and when I do the profiles I retain about a 40-50% of the pairs. SHould I consider using a pairing filter to also retain singletons? I am not shure about the differences that using a "pairing filter" wil have in the overall analysis

Best,

**Closed** 2023-06-06 20:11 UTC
